export { LoginScreen } from './login/login.screen'
export { MainScreen } from './main/main.screen'
export { NotFoundScreen } from './not-found/not-found.screen'
export { RegisterScreen } from './register/register.screen'
export { PokemonScreen } from './pokemon/pokemon.screen'
